### ISSUE TITLE
Base URL namespaces are ignored

### ISSUE THREAD

**Issue by poteto** [stacksocial/munson#4]
```rb
Munson.configure(url: 'http://www.example.com/api/v1') do |c|
  # ...
end

class Foo < Munson::Resource
  self.type = 'foos'
end

Foo.find(1) # tries to get "http://www.example.com/foos/1"
```

**Comment by poteto** [comment]
The namespaces are being stripped out because of https://github.com/stacksocial/munson/blob/master/lib/munson/client.rb#L27 and its interaction with https://github.com/lostisland/faraday/issues/293#issuecomment-22377607:

> If you use the leading slash, it means an absolute path, i.e. "discard whatever path is configured by the URL prefix of this connection".

**Comment by coryodaniel** [comment]
Thanks!

**Comment by mehmetdavut** [comment]
@poteto so usage like: `self.type = 'v1/foos'` is right?
