### ISSUE TITLE
Relationships not working as expected?

### ISSUE THREAD

**Issue by doughsay** [stacksocial/munson#7]
Hi there!  Cool looking gem, I'm considering it for a project.  I'm having trouble with the relationships when testing against a demo json-api app (https://github.com/cerebris/peeps).

I've set up my resources like this:

```ruby
class Contact < Munson::Resource
  self.type = :contacts

  has_many :phone_numbers
  
  attribute :name_first, :string
  attribute :name_last, :string
  attribute :email, :string
  attribute :twitter, :string
end

class PhoneNumber < Munson::Resource
  self.type = :'phone-numbers'

  has_one :contact

  attribute :name, :string
  attribute :phone_number, :string
end
```

And when I attempt to fetch a related resource, I get this message:

```ruby
john = Contact.find(1)
john.phone_numbers
# Munson::RelationshipNotFound:         The relationship `phone_numbers` was called, but does not exist on the document.
#         Relationships available are: phone_numbers
```

```ruby
number = PhoneNumber.find(1)
number.contact
# Munson::RelationshipNotFound:         The relationship `contact` was called, but does not exist on the document.
#         Relationships available are: contact
```

Note also, I had to specify the `type` for phone numbers with a dash in it, but I can't specify the `has_many` relationship with a dash because that throws an error trying to define a method with a dash in it.

**Comment by doughsay** [comment]
Sorry, I may have spoken too soon.

If I `include` the relationship in the `fetch` or `find` call, everything works as expected.  The error message is rather confusing.  Should it not maybe say something like: `The relationship 'contact' was called on the document but was not included.`?

**Comment by coryodaniel** [comment]
Yeah that sounds good, do you want to submit a PR or I can add it this weekend when I have some time.

I also have a ticket open for the route key I haven't had a change to get to yet (I'm not working with dashed routes) https://github.com/stacksocial/munson/issues/2
